name: Publish to S3

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  GIT_BRANCH: ${{ github.head_ref || github.ref_name }}
  GIT_REPO_OWNER: ${{ github.repository_owner }}
  GIT_REPO: ${{ github.repository }}
  AWS_ROLE_ARN: arn:aws:iam::024848458133:role/github_oidc_FuelLabs_verified-assets
  AWS_S3_BUCKET: fuel-prod-verified-assets-origin
  AWS_S3_REGION: us-east-1

jobs:
  publish-to-s3:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_S3_REGION }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install s3cmd tool
        run: pip install -r requirements.txt

      - name: Minify assets JSON
        uses: StefanEnsmann/Minify-JSON-Action@1.1.0
        with:
          input_file: assets.json
          output_file: assets.min.json

      - name: Minify CDN JSON
        uses: StefanEnsmann/Minify-JSON-Action@1.1.0
        with:
          input_file: cdn.json
          output_file: cdn.min.json

      - name: Minify chains JSON
        uses: StefanEnsmann/Minify-JSON-Action@1.1.0
        with:
          input_file: chains.json
          output_file: chains.min.json

      - name: Sync images to S3
        run: s3cmd --delete-removed sync ./images/ s3://${{ env.AWS_S3_BUCKET }}/images/

      - name: Upload CDN JSON
        run: s3cmd put ./cdn.min.json s3://${{ env.AWS_S3_BUCKET }}/cdn.json

      - name: Upload Chains JSON
        run: s3cmd put ./chains.min.json s3://${{ env.AWS_S3_BUCKET }}/chains.json

      - name: Upload Assets JSON
        run: s3cmd put ./assets.min.json s3://${{ env.AWS_S3_BUCKET }}/assets.json
